title:              Bytegeo
email:              support@bytegeo.com
description:        Innovación en Tecnología Geoespacial.
author:             Bytegeo
baseurl:            ""
url:                "https://bytegeo.github.io"

# Social Profiles
twitter_username: bytegeo   
github_username:    
facebook_username:  
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics: 

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site

timezone: Europe/Madrid
languages: ["es", "en"]
default_lang: "es"
exclude_from_localization: ["javascript", "images", "css", "README.md"]
parallel_localization: false

sass:
    sourcemap: never
